version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler123
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduler -d scheduler_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  scheduler:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://scheduler:scheduler123@db:5432/scheduler_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python fastapi_example.py
