version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler123
      POSTGRES_DB: scheduler_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduler -d scheduler_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=scheduler
      - PGPASSWORD=scheduler123
      - PGDATABASE=scheduler_db
    volumes:
      - .:/app
    command: >
      sh -c "pip install pytest pytest-asyncio pytest-cov pytest-timeout &&
             pytest tests/ -v --cov=pg_scheduler --cov-report=term --timeout=30"


